In [26]:
import pandas as pd

In [27]:
animal_df = pd.read_csv('data/tv_animal_sidekicks_102926.csv')
animal_df

,name,show,species,breed_or_type,primary_color,sex,format,talks,anthropomorphic,owner_companion,...,voice_actor,size,signature_trait,data_confidence,image_url,image_source,image_note,image_file,silhouette_file,silhouette_quality
0,Kit,Charmed,Cat,Siamese,Cream with dark points,Female,Live action,No,No,The Halliwell sisters,...,NaN,Small,Witch's familiar guarding the Charmed Ones,Medium,https://static.wikia.nocookie.net/charmed/imag...,Charmed Wiki (Fandom),NaN,images/kit.jpg,silhouettes/kit.png,fair
1,Salem Saberhagen,Sabrina the Teenage Witch,Cat,American Shorthair,Black,Male,Live action + puppet,Yes,Yes,Sabrina Spellman,...,Nick Bakay,Small,500-year-old warlock cursed for trying to take...,High,https://static.wikia.nocookie.net/thesabrinath...,Sabrina Wiki (Fandom),NaN,images/salem_saberhagen.png,silhouettes/salem_saberhagen.png,good
2,Brian Griffin,Family Guy,Dog,Labrador mix,White,Male,Animated,Yes,Yes,Peter Griffin,...,Seth MacFarlane,Medium,Martini-drinking aspiring novelist,High,https://upload.wikimedia.org/wikipedia/en/1/12...,Wikipedia,NaN,images/brian_griffin.png,silhouettes/brian_griffin.png,good
3,Lassie,Lassie,Dog,Rough Collie,Sable and white,Female,Live action,No,No,Timmy Martin,...,NaN,Large,Rescues people in danger,High,https://upload.wikimedia.org/wikipedia/commons...,Wikipedia,NaN,images/lassie.jpg,silhouettes/lassie.png,good
4,Mister Ed,Mister Ed,Horse,Palomino,Golden with white mane,Male,Live action,Yes,No,Wilbur Post,...,Allan Lane,Large,Talks only to Wilbur,High,https://upload.wikimedia.org/wikipedia/commons...,Wikipedia,Cast photo; horse shown with human actors,images/mister_ed.jpg,silhouettes/mister_ed.png,fair
5,Arnold Ziffel,Green Acres,Pig,Domestic pig,Pink and white,Male,Live action,No,Yes,Fred and Doris Ziffel,...,NaN,Medium,Attends school and watches the news,High,https://upload.wikimedia.org/wikipedia/commons...,Wikipedia,NaN,images/arnold_ziffel.jpg,silhouettes/arnold_ziffel.png,fair
6,Scooby-Doo,"Scooby-Doo, Where Are You!",Dog,Great Dane,Brown with black spots,Male,Animated,Limited,Partly,Shaggy Rogers,...,Don Messick,Large,Cowardly but solves mysteries for Scooby Snacks,High,https://upload.wikimedia.org/wikipedia/en/5/53...,Wikipedia,NaN,images/scooby_doo.png,silhouettes/scooby_doo.png,good
7,Snoopy,Peanuts specials,Dog,Beagle,White with black ears,Male,Animated,No (thought bubbles),Yes,Charlie Brown,...,Bill Melendez (vocal effects),Small,Imagines dogfights with the Red Baron,High,https://upload.wikimedia.org/wikipedia/en/5/53...,Wikipedia,NaN,images/snoopy.png,silhouettes/snoopy.png,good
8,Eddie Crane,Frasier,Dog,Jack Russell Terrier,White and tan,Male,Live action,No,No,Martin Crane,...,NaN,Small,Stares at Frasier,High,https://upload.wikimedia.org/wikipedia/en/2/28...,Wikipedia,"Magazine cover of Moose, the dog who played Eddie",images/eddie_crane.jpg,silhouettes/eddie_crane.png,poor
9,Dino,The Flintstones,Dinosaur,Snorkasaurus,Purple with black spots,Male,Animated,No,No,Fred Flintstone,...,Mel Blanc,Large,Tackles Fred with kisses at the door,High,https://upload.wikimedia.org/wikipedia/en/f/f7...,Wikipedia,NaN,images/dino.gif,silhouettes/dino.png,good
10,Marcel,Friends,Monkey,White-headed capuchin,Brown and cream,Male,Live action,No,No,Ross Geller,...,NaN,Small,"Plays ""The Lion Sleeps Tonight"" on repeat",High,https://static.wikia.nocookie.net/friends/imag...,Friends Wiki (Fandom),Marcel shown with Ross,images/marcel.jpg,silhouettes/marcel.png,poor
11,Chick,Friends,Bird,Chicken,Yellow,Female,Live action,No,No,Chandler and Joey,...,NaN,Small,Joey and Chandler's co-pet with the Duck,Medium,https://static.wikia.nocookie.net/friends/imag...,Friends Wiki (Fandom),Shows the Duck; no separate Chick image found,images/chick.jpg,silhouettes/chick.png,good
12,Duck,Friends,Bird,Domestic duck,White,Male,Live action,No,No,Chandler and Joey,...,NaN,Small,Sat in the bathtub with Joey,Medium,https://static.wikia.nocookie.net/friends/imag...,Friends Wiki (Fandom),NaN,images/duck.jpg,silhouettes/duck.png,good
13,Flipper,Flipper,Dolphin,Bottlenose dolphin,Gray,Male,Live action,No,No,Porter Ricks and sons,...,NaN,Large,Rescues people at sea,High,https://upload.wikimedia.org/wikipedia/en/d/d1...,Wikipedia,Show title card,images/flipper.jpg,silhouettes/flipper.png,poor
14,Murray,Mad About You,Dog,Border Collie mix,Tan and white,Male,Live action,No,No,Paul and Jamie Buchman,...,NaN,Medium,Notoriously dim-witted,Medium,https://static.wikia.nocookie.net/madaboutyou/...,Mad About You Wiki (Fandom),NEEDS CHECK: episode still of the human cast; ...,images/murray.jpg,silhouettes/murray.png,fair
15,Stella,Modern Family,Dog,French Bulldog,Brindle,Female,Live action,No,No,Jay Pritchett,...,NaN,Small,Jay loves her more than people,Medium,https://static.wikia.nocookie.net/modernfamily...,Modern Family Wiki (Fandom),NaN,images/stella.jpg,silhouettes/stella.png,good
16,Clarence,Daktari,Lion,African lion,Tawny,Male,Live action,No,No,Dr. Marsh Tracy,...,NaN,Large,Cross-eyed and gentle,Medium,https://upload.wikimedia.org/wikipedia/en/9/99...,Wikipedia,Poster for the 1965 film that spawned Daktari,images/clarence.jpg,silhouettes/clarence.png,poor
17,Santa's Little Helper,The Simpsons,Dog,Greyhound,Tan,Male,Animated,No,No,Bart Simpson,...,Frank Welker (vocal effects),Medium,Failed racing dog adopted at Christmas,High,https://upload.wikimedia.org/wikipedia/en/8/8a...,Wikipedia,NaN,images/santa_s_little_helper.png,silhouettes/santa_s_little_helper.png,good
18,Snowball II,The Simpsons,Cat,Domestic shorthair,Black,Female,Animated,No,No,Lisa Simpson,...,NaN,Small,Replaced by a series of identical cats,High,https://static.wikia.nocookie.net/simpsons/ima...,Simpsons Wiki (Fandom),NaN,images/snowball_ii.png,silhouettes/snowball_ii.png,fair
19,Comet,Full House,Dog,Golden Retriever,Golden,Male,Live action,No,No,The Tanner family,...,NaN,Large,Same hair color as the Tanner girls,High,https://static.wikia.nocookie.net/fullhouse/im...,Full House Wiki (Fandom),NaN,images/comet.jpg,silhouettes/comet.png,poor
20,Vincent,Lost,Dog,Labrador Retriever,Yellow,Male,Live action,No,No,Walt Lloyd,...,NaN,Large,Survived the plane crash,High,https://static.wikia.nocookie.net/lostpedia/im...,Lostpedia (Fandom),NaN,images/vincent.jpg,silhouettes/vincent.png,poor
21,Rin Tin Tin,The Adventures of Rin Tin Tin,Dog,German Shepherd,Black and tan,Male,Live action,No,No,Rusty,...,NaN,Large,Heroic cavalry dog,High,https://upload.wikimedia.org/wikipedia/commons...,Wikipedia,"Photo of the original 1920s film dog, not the ...",images/rin_tin_tin.jpg,silhouettes/rin_tin_tin.png,fair
22,Gentle Ben,Gentle Ben,Bear,American black bear,Black,Male,Live action,No,No,Mark Wedloe,...,NaN,Large,Huge but harmless,High,https://upload.wikimedia.org/wikipedia/en/5/56...,Wikipedia,Cover of the novel the show was based on,images/gentle_ben.jpg,silhouettes/gentle_ben.png,fair
23,Cheddar,Brooklyn Nine-Nine,Dog,Pembroke Welsh Corgi,Red and white,Male,Live action,No,No,Raymond Holt and Kevin Cozner,...,NaN,Small,Holt's beloved pampered pup,Medium,https://static.wikia.nocookie.net/brooklynnine...,Brooklyn Nine-Nine Wiki (Fandom),NaN,images/cheddar.jpg,silhouettes/cheddar.png,fair
24,Ghost,Game of Thrones,Wolf,Direwolf,White with red eyes,Male,Live action + CGI,No,No,Jon Snow,...,NaN,Large,Silent albino direwolf,High,https://static.wikia.nocookie.net/gameofthrone...,Game of Thrones Wiki (Fandom),NaN,images/ghost.png,silhouettes/ghost.png,good
25,Gary the Snail,SpongeBob SquarePants,Snail,Sea snail,Pink shell and blue body,Male,Animated,No (meows),No,SpongeBob SquarePants,...,Tom Kenny,Small,Meows like a cat,High,https://static.wikia.nocookie.net/spongebob/im...,SpongeBob Wiki (Fandom),Transparent PNG,images/gary_the_snail.png,silhouettes/gary_the_snail.png,good
26,Klaus Heissler,American Dad!,Fish,Goldfish,Orange,Male,Animated,Yes,Yes,The Smith family,...,Dee Bradley Baker,Small,East German athlete's brain in a fish,High,https://upload.wikimedia.org/wikipedia/en/2/24...,Wikipedia,NaN,images/klaus_heissler.png,silhouettes/klaus_heissler.png,fair
27,Garfield,Garfield and Friends,Cat,Orange tabby,Orange with black stripes,Male,Animated,Yes (thoughts),Yes,Jon Arbuckle,...,Lorenzo Music,Medium,Loves lasagna and hates Mondays,High,https://upload.wikimedia.org/wikipedia/en/b/bc...,Wikipedia,SVG original; image_file is a converted PNG,images/garfield.png,silhouettes/garfield.png,good
28,Odie,Garfield and Friends,Dog,Beagle mix,Yellow with brown ears,Male,Animated,No,No,Jon Arbuckle,...,Gregg Berger,Medium,Giant slobbery tongue,High,https://static.wikia.nocookie.net/garfield/ima...,Garfield Wiki (Fandom),NaN,images/odie.jpg,silhouettes/odie.png,good
29,Wishbone,Wishbone,Dog,Jack Russell Terrier,White with brown patches,Male,Live action,Yes,Partly,Joe Talbot,...,Larry Brantley,Small,Imagines himself in classic novels,High,https://static.wikia.nocookie.net/wishbone/ima...,Wishbone Wiki (Fandom),Includes show logo,images/wishbone.gif,silhouettes/wishbone.png,fair
30,Tiger,The Brady Bunch,Dog,Mixed breed,Tan,Male,Live action,No,No,The Brady family,...,NaN,Medium,Quietly vanished after early seasons,Medium,https://static.wikia.nocookie.net/thebradybunc...,Brady Bunch Wiki (Fandom),NaN,images/tiger.jpg,silhouettes/tiger.png,poor
31,Buck,Married... with Children,Dog,Briard,Tan,Male,Live action,Yes (inner voice),No,Al Bundy,...,Kevin Curran,Large,Sarcastic inner monologue,High,https://static.wikia.nocookie.net/marriedwithc...,Married... with Children Wiki (Fandom),NaN,images/buck.jpg,silhouettes/buck.png,poor
32,Jake the Dog,Adventure Time,Dog,Bulldog (magical),Yellow-orange,Male,Animated,Yes,Yes,Finn the Human,...,John DiMaggio,Medium (stretchy),Can stretch into any shape,High,https://upload.wikimedia.org/wikipedia/commons...,Wikipedia,SVG original; image_file is a converted PNG,images/jake_the_dog.png,silhouettes/jake_the_dog.png,good
33,Courage,Courage the Cowardly Dog,Dog,Beagle (cartoon),Pink,Male,Animated,Limited,Partly,Muriel Bagge,...,Marty Grabstein,Small,Terrified but always saves his owners,High,https://static.wikia.nocookie.net/courage/imag...,Courage Wiki (Fandom),NaN,images/courage.png,silhouettes/courage.png,good
34,Bandit,Jonny Quest,Dog,Bulldog,White with black eye patch,Male,Animated,No,No,Jonny Quest,...,Don Messick,Small,Mask-like eye marking,High,https://static.wikia.nocookie.net/jonnyquest/i...,Jonny Quest Wiki (Fandom),NaN,images/bandit.png,silhouettes/bandit.png,fair
35,Astro,The Jetsons,Dog,Great Dane,Gray-brown with dark spots,Male,Animated,Limited,Partly,George Jetson,...,Don Messick,Large,"Says ""Ruh-roh, Reorge""",High,https://static.wikia.nocookie.net/hanna-barber...,Hanna-Barbera Wiki (Fandom),NaN,images/astro.png,silhouettes/astro.png,good
36,Spot,Star Trek: The Next Generation,Cat,Orange tabby,Orange,Female (originally male),Live action,No,No,Data,...,NaN,Small,Android's cat who inspired an ode,High,https://static.wikia.nocookie.net/memoryalpha/...,Memory Alpha (Fandom),NaN,images/spot.jpg,silhouettes/spot.png,fair
37,Porthos,Star Trek: Enterprise,Dog,Beagle,Tricolor,Male,Live action,No,No,Captain Jonathan Archer,...,NaN,Small,Lives on a starship and loves cheese,High,https://static.wikia.nocookie.net/memoryalpha/...,Memory Alpha (Fandom),NaN,images/porthos.jpg,silhouettes/porthos.png,poor
38,K-9,Doctor Who,Robot dog,Mechanical,Gray metallic,Male,Live action (prop),Yes,No,The Doctor,...,John Leeson,Small,Laser nose and computer brain,High,https://static.wikia.nocookie.net/tardis/image...,TARDIS Wiki (Fandom),NaN,images/k_9.jpg,silhouettes/k_9.png,poor
39,Max,How the Grinch Stole Christmas!,Dog,Mixed breed,Brown,Male,Animated,No,No,The Grinch,...,NaN,Small,Wears a single antler as a reindeer,High,https://static.wikia.nocookie.net/seuss/images...,Dr. Seuss Wiki (Fandom),NaN,images/max.png,silhouettes/max.png,good
40,Toothless,DreamWorks Dragons,Dragon,Night Fury,Black,Male,Animated,No,No,Hiccup Haddock,...,NaN,Large,Flies with a prosthetic tail fin,High,https://static.wikia.nocookie.net/howtotrainyo...,How to Train Your Dragon Wiki (Fandom),NaN,images/toothless.png,silhouettes/toothless.png,good
41,Perry the Platypus,Phineas and Ferb,Platypus,Duck-billed platypus,Teal,Male,Animated,No (chatters),Partly,Phineas and Ferb,...,Dee Bradley Baker,Small,Secret agent in a fedora (Agent P),High,https://static.wikia.nocookie.net/phineasandfe...,Phineas and Ferb Wiki (Fandom),NaN,images/perry_the_platypus.png,silhouettes/perry_the_platypus.png,fair
42,Bluey Heeler,Bluey,Dog,Blue Heeler (Australian Cattle Dog),Blue,Female,Animated,Yes,Yes,The Heeler family,...,NaN,Medium,Turns everyday life into imaginative games,High,https://static.wikia.nocookie.net/blueypedia/i...,Bluey Wiki (Fandom),NaN,images/bluey_heeler.png,silhouettes/bluey_heeler.png,good
43,Mr. Peanutbutter,BoJack Horseman,Dog,Yellow Labrador Retriever,Yellow,Male,Animated,Yes,Yes,BoJack Horseman,...,Paul F. Tompkins,Large,Relentlessly cheerful sitcom star,High,https://static.wikia.nocookie.net/bojackhorsem...,BoJack Horseman Wiki (Fandom),NaN,images/mr_peanutbutter.png,silhouettes/mr_peanutbutter.png,good
44,Kermit the Frog,The Muppet Show,Frog,Muppet frog,Green,Male,Puppet,Yes,Yes,Miss Piggy,...,Jim Henson,Small,Says it's not easy being green,High,https://static.wikia.nocookie.net/muppet/image...,Muppet Wiki (Fandom),NaN,images/kermit_the_frog.jpg,silhouettes/kermit_the_frog.png,fair
45,Peppa Pig,Peppa Pig,Pig,Domestic pig,Pink,Female,Animated,Yes,Yes,George Pig,...,Harley Bird,Small,Loves jumping in muddy puddles,High,https://static.wikia.nocookie.net/peppapig/ima...,Peppa Pig Wiki (Fandom),NaN,images/peppa_pig.png,silhouettes/peppa_pig.png,good
46,Clifford,Clifford the Big Red Dog,Dog,Giant mixed breed,Red,Male,Animated,Yes,Partly,Emily Elizabeth Howard,...,John Ritter,Giant,Grew huge because he was loved so much,High,https://static.wikia.nocookie.net/clifford/ima...,Clifford Wiki (Fandom),NaN,images/clifford.png,silhouettes/clifford.png,good
47,Arthur Read,Arthur,Aardvark,Anthropomorphic aardvark,Yellow-brown,Male,Animated,Yes,Yes,Buster Baxter,...,Michael Yarmush,Small,Round glasses and a yellow sweater,Medium,https://static.wikia.nocookie.net/arthur/image...,Arthur Wiki (Fandom),NaN,images/arthur_read.png,silhouettes/arthur_read.png,fair
48,Ein,Cowboy Bebop,Dog,Pembroke Welsh Corgi,Tan and white,Male,Animated,No,No,Edward and Spike Spiegel,...,Kōichi Yamadera,Small,Genetically enhanced data dog,High,https://static.wikia.nocookie.net/cowboybebop/...,Cowboy Bebop Wiki (Fandom),NaN,images/ein.png,silhouettes/ein.png,fair
49,Seymour,Futurama,Dog,Mixed breed,Brown,Male,Animated,No,No,Philip J. Fry,...,NaN,Small,Waited years for Fry to come home,Medium,https://static.wikia.nocookie.net/enfuturama/i...,Futurama Wiki (Fandom),NaN,images/seymour.jpg,silhouettes/seymour.png,fair
50,Stimpy,The Ren & Stimpy Show,Cat,Manx,Red and white,Male,Animated,Yes,Yes,Ren Höek,...,Billy West,Medium,"Happy, dim-witted cat with a blue nose",High,https://static.wikia.nocookie.net/renandstimpy...,Ren & Stimpy Wiki (Fandom),WebP original; image_file is a converted PNG,images/stimpy.png,silhouettes/stimpy.png,good

In [30]:
animal_simple_df = animal_df[['name', 'show', 'species', 'image_url']]

name = animal_simple_df['name'][0]
show = animal_simple_df['show'][0]
species = animal_simple_df['species'][0]
print(f"{name}, {show}, {species}")

animal_simple_df

Kit, Charmed, Cat

,name,show,species,image_url
0,Kit,Charmed,Cat,https://static.wikia.nocookie.net/charmed/imag...
1,Salem Saberhagen,Sabrina the Teenage Witch,Cat,https://static.wikia.nocookie.net/thesabrinath...
2,Brian Griffin,Family Guy,Dog,https://upload.wikimedia.org/wikipedia/en/1/12...
3,Lassie,Lassie,Dog,https://upload.wikimedia.org/wikipedia/commons...
4,Mister Ed,Mister Ed,Horse,https://upload.wikimedia.org/wikipedia/commons...
5,Arnold Ziffel,Green Acres,Pig,https://upload.wikimedia.org/wikipedia/commons...
6,Scooby-Doo,"Scooby-Doo, Where Are You!",Dog,https://upload.wikimedia.org/wikipedia/en/5/53...
7,Snoopy,Peanuts specials,Dog,https://upload.wikimedia.org/wikipedia/en/5/53...
8,Eddie Crane,Frasier,Dog,https://upload.wikimedia.org/wikipedia/en/2/28...
9,Dino,The Flintstones,Dinosaur,https://upload.wikimedia.org/wikipedia/en/f/f7...
10,Marcel,Friends,Monkey,https://static.wikia.nocookie.net/friends/imag...
11,Chick,Friends,Bird,https://static.wikia.nocookie.net/friends/imag...
12,Duck,Friends,Bird,https://static.wikia.nocookie.net/friends/imag...
13,Flipper,Flipper,Dolphin,https://upload.wikimedia.org/wikipedia/en/d/d1...
14,Murray,Mad About You,Dog,https://static.wikia.nocookie.net/madaboutyou/...
15,Stella,Modern Family,Dog,https://static.wikia.nocookie.net/modernfamily...
16,Clarence,Daktari,Lion,https://upload.wikimedia.org/wikipedia/en/9/99...
17,Santa's Little Helper,The Simpsons,Dog,https://upload.wikimedia.org/wikipedia/en/8/8a...
18,Snowball II,The Simpsons,Cat,https://static.wikia.nocookie.net/simpsons/ima...
19,Comet,Full House,Dog,https://static.wikia.nocookie.net/fullhouse/im...
20,Vincent,Lost,Dog,https://static.wikia.nocookie.net/lostpedia/im...
21,Rin Tin Tin,The Adventures of Rin Tin Tin,Dog,https://upload.wikimedia.org/wikipedia/commons...
22,Gentle Ben,Gentle Ben,Bear,https://upload.wikimedia.org/wikipedia/en/5/56...
23,Cheddar,Brooklyn Nine-Nine,Dog,https://static.wikia.nocookie.net/brooklynnine...
24,Ghost,Game of Thrones,Wolf,https://static.wikia.nocookie.net/gameofthrone...
25,Gary the Snail,SpongeBob SquarePants,Snail,https://static.wikia.nocookie.net/spongebob/im...
26,Klaus Heissler,American Dad!,Fish,https://upload.wikimedia.org/wikipedia/en/2/24...
27,Garfield,Garfield and Friends,Cat,https://upload.wikimedia.org/wikipedia/en/b/bc...
28,Odie,Garfield and Friends,Dog,https://static.wikia.nocookie.net/garfield/ima...
29,Wishbone,Wishbone,Dog,https://static.wikia.nocookie.net/wishbone/ima...
30,Tiger,The Brady Bunch,Dog,https://static.wikia.nocookie.net/thebradybunc...
31,Buck,Married... with Children,Dog,https://static.wikia.nocookie.net/marriedwithc...
32,Jake the Dog,Adventure Time,Dog,https://upload.wikimedia.org/wikipedia/commons...
33,Courage,Courage the Cowardly Dog,Dog,https://static.wikia.nocookie.net/courage/imag...
34,Bandit,Jonny Quest,Dog,https://static.wikia.nocookie.net/jonnyquest/i...
35,Astro,The Jetsons,Dog,https://static.wikia.nocookie.net/hanna-barber...
36,Spot,Star Trek: The Next Generation,Cat,https://static.wikia.nocookie.net/memoryalpha/...
37,Porthos,Star Trek: Enterprise,Dog,https://static.wikia.nocookie.net/memoryalpha/...
38,K-9,Doctor Who,Robot dog,https://static.wikia.nocookie.net/tardis/image...
39,Max,How the Grinch Stole Christmas!,Dog,https://static.wikia.nocookie.net/seuss/images...
40,Toothless,DreamWorks Dragons,Dragon,https://static.wikia.nocookie.net/howtotrainyo...
41,Perry the Platypus,Phineas and Ferb,Platypus,https://static.wikia.nocookie.net/phineasandfe...
42,Bluey Heeler,Bluey,Dog,https://static.wikia.nocookie.net/blueypedia/i...
43,Mr. Peanutbutter,BoJack Horseman,Dog,https://static.wikia.nocookie.net/bojackhorsem...
44,Kermit the Frog,The Muppet Show,Frog,https://static.wikia.nocookie.net/muppet/image...
45,Peppa Pig,Peppa Pig,Pig,https://static.wikia.nocookie.net/peppapig/ima...
46,Clifford,Clifford the Big Red Dog,Dog,https://static.wikia.nocookie.net/clifford/ima...
47,Arthur Read,Arthur,Aardvark,https://static.wikia.nocookie.net/arthur/image...
48,Ein,Cowboy Bebop,Dog,https://static.wikia.nocookie.net/cowboybebop/...
49,Seymour,Futurama,Dog,https://static.wikia.nocookie.net/enfuturama/i...
50,Stimpy,The Ren & Stimpy Show,Cat,https://static.wikia.nocookie.net/renandstimpy...

In [35]:
import random
import ipywidgets as widgets                                  # the widget library (buttons, labels, boxes)
from IPython.display import display, clear_output             # display() shows widgets; clear_output() erases printed text
from IPython.display import Image as IPImage                  # `as` gives it a unique name, so PIL's Image can't replace it
import requests
from PIL import Image
import io

# define the function for the game
def playGame():

###################################################################################################

### SETUP CODE ###

    df = animal_simple_df                                     # simplifying variable for dataframe


    # a dictionary holding every value that changes during the game
    state = {
        'modifier': '',                                       # the exact button text that counts as the correct answer
        'success': False,                                     # True once the current question has been answered correctly
        'current': None,                                      # which game is on screen: 1 or 2
        'score': 0,                                           # number of questions answered correctly; starts at 0
        'missed': False,                                       # True if a wrong answer was clicked on the current question
        'row': None                                           # the DataFrame row the current question was built from
    }

    # helper function that creates one button with the standard settings
    def make_button(text, style='primary'):
        return widgets.Button(
            description=text,
            button_style=style,
            layout=widgets.Layout(width='500px')
        )

    question = widgets.Label()                                # a text widget that displays the current question; its text is set later through .value
    answer_buttons = [make_button(x) for x in 'abcd']         # list comprehension: runs make_button once per character in 'abcd', giving a list of 4 buttons
    nextButton = make_button('Next', style='')
    output = widgets.Output()
    imageBox = widgets.Output(                                # separate output area for the picture; margin adds a 20px gap on its left
                layout=widgets.Layout(margin='0 0 0 20px'))  
    scoreLabel = widgets.Label()                              # text widget that shows the current score
    resetButton = make_button('Start over', style='warning')  # 'warning' gives an orange button, so it stands apart from the answers
    startButton = make_button('Play', style='success')  # green so it stands out as the way in

    
    title = widgets.HTML("""
<pre style="font-family: monospace; line-height: 1.1; font-size: 14px;">
   🐶 🐱 🐰 🦜 🐢 🐴 🐷 🐭 🦊 🐸

█████  ████   ███  █   █  ███   ███ 
  █    █   █   █   █   █   █   █   █
  █    ████    █   █   █   █   █████
  █    █  █    █    █ █    █   █   █
  █    █   █  ███    █    ███  █   █

   🐮 🐵 🐧 🦁 🐯 🐨 🐼 🐹 🦉 🐍
</pre>
<h3>Animal Characters In Popular Media</h3>
""")   
    
    

    # updates the score label to match state['score']
    def updateScore():
        scoreLabel.value = f"Score: {state['score']}"

    # helper that turns one animal's row into button text like "Kit, from Charmed"
    def label(row):
        return f"{row['name']}, from {row['show']}"

    # builds the 4 options for game1: 3 wrong values from a column plus the correct one
    def pickOptions(column, correct):

        # step by step, inside to outside:
        #   df[column] != correct   -> a "boolean mask": a Series of True/False, one per row, True wherever the value is NOT the correct answer
        #   df.loc[mask, column]    -> .loc selects by labels/conditions: rows where the mask is True, and only the given column, giving a Series of wrong answers
        #   .unique()               -> removes duplicates (so "Dog" appears once, not five times); returns a NumPy array, not a Series
        #   .tolist()               -> converts that array into a plain Python list

        wrong = df.loc[df[column] != correct, column].unique().tolist()
        options = random.sample(wrong, 3) + [correct]         # random.sample(list, 3) picks 3 *different* items at random; then add the correct answer
        random.shuffle(options)                               # shuffle the list in place so the correct answer isn't always the last button
        return options

    # builds the 4 options for game2: 3 animals of other species (one per species) plus the correct animal
    def pickAnimalOptions(row):
        others = (                                            # wrapping the expression in parentheses lets us split a "method chain" across several lines
            df[df['species'] != row['species']]               # boolean mask again: keep only rows whose species differs from the correct animal's (df[mask] filters rows and keeps every column)
                  .sample(frac=1)                             # .sample(frac=1) takes a random sample of 100% of the rows, which in practice shuffles the whole DataFrame
                  .drop_duplicates('species')                 # drop_duplicates('species') keeps only the FIRST row for each species value; because we shuffled first, which dog/cat/etc. is "first" is random each time
                  .head(3)                                    # .head(3) keeps the first 3 rows of what's left: 3 animals, 3 different species
        )

        # .iterrows() loops over a DataFrame one row at a time, yielding (index, row) pairs;
        # `_` is a Python convention for "a value I don't need" (here, the index);
        # the list comprehension labels each row, then we add the correct animal's label

        options = [label(r) for _, r in others.iterrows()] + [label(row)]
        random.shuffle(options)                               # shuffle so the correct animal lands on a random button
        return options                                        # hand back the 4 shuffled labels

    # loads a question onto the screen: question text, correct answer, and 4 options
    def setQuestion(text, correct, options):
        for button, option in zip(answer_buttons, options):   # zip() pairs items from two lists side by side: (button1, option1), (button2, option2), ...
            button.description = option                       # put this option's text on the button
            button.button_style = 'primary'                   # reset the color to blue (it may be green/red from the last question)

        # everything indented under this line is directed into the output box
        with output:
            clear_output()                                    # erase the previous "That's right!" / "Incorrect" message
        with imageBox:
            clear_output()                                    # erase the previous picture
        state['success'] = False                              # this new question hasn't been answered yet
        state['missed'] = False                               # ...and hasn't been missed yet either
        state['modifier'] = correct                           # remember which button text is correct
        question.value = text                                 # display the question text in the Label widget

###################################################################################################

### GAME 1 MECHANICS ###

    # game 1: show an animal, ask for its species
    def game1():
        state['current'] = 1                                  # record that game 1 is on screen, so Next knows to switch to game 2
        row = df.sample(1).iloc[0]                            # pick a random row
        state['row'] = row                                    # remember it, so the answer handler can show its image
        # load the question: text, correct answer (that row's species), and the 4 options
        setQuestion(f"What species is the animal {row['name']} from the show {row['show']}?",
                    row['species'], pickOptions('species', row['species']))

###################################################################################################

### GAME 2 MECHANICS ###

    # game 2: name a species, ask which animal belongs to it
    def game2():
        state['current'] = 2                                   # record that game 2 is on screen
        row = df.sample(1).iloc[0]                             # pick a random animal; its species becomes the question
        state['row'] = row   
        
        setQuestion(f"Which of these is a {row['species'].lower()}?",
                    label(row), pickAnimalOptions(row))        # correct answer: this animal's label, e.g. "Kit, from Charmed"

###################################################################################################

### BUTTON MECHANICS ###

    # runs whenever an answer button is clicked; ipywidgets passes the clicked button in as `b`
    def on_answer_click(b):
        if state['success']:                                   # if this question was already answered correctly, ignore further clicks
            return
        with output:
            clear_output()
            if b.description == state['modifier']:             # compare the clicked button's text against the stored correct answer
                b.button_style = 'success'                     # correct: turn the button green
                state['success'] = True                        # remember that this question is solved (this unlocks Next)
                if not state['missed']:                        # only award a point if there were no wrong guesses first
                    state['score'] += 1
                    updateScore()
                    print("That's right! Press Next to continue.")
                else:
                    print("That's right, but no point this time. Press Next to continue.")

                url = state['row']['image_url']                # look up the image URL for this question's animal
                if pd.notna(url):
                    with imageBox:                             # direct the image into the right-hand box instead of the message box
                        display(IPImage(url=url, width=300))
            else:
                b.button_style = 'danger'                      # wrong: turn the button red
                state['missed'] = True                         # remember the miss, so a later correct answer won't score
                print("Incorrect, try again")

    # runs whenever the Next button is clicked
    def on_next_click(b):
        if not state['success']:                               # `not` flips True/False: this checks "has the question NOT been solved yet?"
            with output:                                       # send the warning into the output box
                clear_output()                                 # remove the previous message
                print("Answer the question first!")
            return                                             # stop without switching games

        game2() if state['current'] == 1 else game1()          # conditional expression (a one-line if/else): run game2 if we're on game 1, otherwise game1

    # runs whenever the "start game over" button is clicked: resets the score and returns to the title screen
    def on_reset_click(b):
        state['score'] = 0                                     # set the score back to 0
        updateScore()                                          # refresh the label so it reads "Score: 0" next time the game shows
        with output:
            clear_output()                                     # erase the previous message
        with imageBox:
            clear_output()                                     # erase the previous picture
        screen.children = [titleScreen]                        # swap the game UI out and the title screen back in

    # runs when the start button is clicked: swaps the title screen for the game
    def on_start_click(b):
        game1()                                                # load the first question
        updateScore()                                          # show "Score: 0"
        screen.children = [gameUI]                             # replace the title screen with the game UI


    for button in answer_buttons:                              # loop over the 4 answer buttons
        button.on_click(on_answer_click)
    nextButton.on_click(on_next_click)                         # NOT indented under the loop: register it once
    resetButton.on_click(on_reset_click)
    startButton.on_click(on_start_click)

###################################################################################################

### GAME INITIALIZATION ###

    titleScreen = widgets.VBox([title, startButton])           # the title screen: heading + start button

    leftColumn = widgets.VBox([scoreLabel, question, *answer_buttons,
                               nextButton, resetButton, output])  # everything that was in the game screen before, stacked vertically

    gameUI = widgets.HBox([leftColumn, imageBox])             # HBox places its children side by side: controls on the left, picture on the right
    
    screen = widgets.VBox([titleScreen])                       # one container that's always on screen; its contents get swapped

    display(screen)                                            # display the container once

###################################################################################################

### GAME START! ###

playGame()                                                     # start the game upon running this code block

VBox(children=(VBox(children=(HTML(value='\n<pre style="font-family: monospace; line-height: 1.1; font-size: 1…